name: docai
description: "An app to heal the world"

version: 6.1.4+49

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  flutter_inappwebview: ^6.1.5
  intl: ^0.20.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  http: ^1.6.0
  flutter_markdown: ^0.7.7+1
  uuid: ^4.5.1
  timeago: ^3.7.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/xmas.png
    - assets/logo/logo compress.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/xmas.png"
  min_sdk_android: 16
  web:
    generate: true
    image_path: "assets/logo/xmas.png"
    background_color: "#FFF"
    theme_color: "#000"
  windows:
    generate: true
    image_path: "assets/logo/xmas.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/xmas.png"
