name: docai
description: "An app to heal the world"

version: 0.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.0
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  app_links: ^3.4.5

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - ./.env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpg"
  min_sdk_android: 16
  web:
    generate: true
    image_path: "assets/logo/logo transparent.png"
    background_color: "#FFF"
    theme_color: "#000"
  windows:
    generate: true
    image_path: "assets/logo/logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.jpg"